import { ContainerModule } from "inversify";
import { Model } from "mongoose";
import { ISetPassWordUseCase } from "../../../application/usecases/auth/interface/set.password.interface";
import { ILoginUseCase } from "../../../application/usecases/auth/interface/login.interface";
import { ILogoutUseCase } from "../../../application/usecases/auth/interface/logout.interface";
import { IRefreshUseCase } from "../../../application/usecases/auth/interface/refresh.interface";
import { SetPasswordUseCase } from "../../../application/usecases/auth/implemetation/set.password.usecase";
import { LoginUseCase } from "../../../application/usecases/auth/implemetation/login.usecase";
import { LogoutUseCase } from "../../../application/usecases/auth/implemetation/logout.usecase";
import { RefreshUseCase } from "../../../application/usecases/auth/implemetation/refresh.usecase";
import { IForgotPasswordUseCase } from "../../../application/usecases/auth/interface/forgot.password.interface";
import { IVerifyForgotOtpUseCase } from "../../../application/usecases/auth/interface/verifyforgot.otp.interface";
import { IResetPasswordUseCase } from "../../../application/usecases/auth/interface/reset.password.interface";
import { ForgotPasswordUseCase } from "../../../application/usecases/auth/implemetation/forgot.password.usecase";
import { VerifyForgotPasswordOtpUseCase } from "../../../application/usecases/auth/implemetation/verifyforgototp.usecase";
import { ResetPasswordUseCase } from "../../../application/usecases/auth/implemetation/reset.password.usecase";
import { IUserRepository } from "../../../domain/interfaces/IUserRepository";
import { AuthController } from "../../../presentation/express/controllers/auth.controller";
import { IUser } from "../../db/interface/user.interface";
import { UserModel } from "../../db/models/user.model";
import { UserRepository } from "../../db/repository/implements/user.repository";
import { UserPersistenceMapper } from "../../mappers/user.mapper";
import { AUTH_TYPES } from "../types/auth/auth.types";
import { USER_TYPES } from "../types/user/user.types";

export const UserModule = new ContainerModule(({ bind }) => {
  bind<IUserRepository>(USER_TYPES.IUserRepository).to(UserRepository);
  bind<UserPersistenceMapper>(USER_TYPES.UserPersistenceMapper).to(UserPersistenceMapper);
  bind<Model<IUser>>(USER_TYPES.userModel).toConstantValue(UserModel);
  bind<AuthController>(USER_TYPES.AuthController).to(AuthController);
  bind<ILoginUseCase>(USER_TYPES.ILoginUseCase).to(LoginUseCase);
  bind<ILogoutUseCase>(AUTH_TYPES.ILogoutUseCase).to(LogoutUseCase);
  bind<ISetPassWordUseCase>(AUTH_TYPES.ISetPasswordUseCase).to(SetPasswordUseCase);
  bind<IForgotPasswordUseCase>(AUTH_TYPES.IForgotPasswordUseCase).to(ForgotPasswordUseCase);
  bind<IVerifyForgotOtpUseCase>(AUTH_TYPES.IVerifyForgotOtpUseCase).to(VerifyForgotPasswordOtpUseCase);
  bind<IResetPasswordUseCase>(AUTH_TYPES.IResetPasswordUseCase).to(ResetPasswordUseCase);
  bind<IRefreshUseCase>(AUTH_TYPES.IRefreshUseCase).to(RefreshUseCase);
});
